"use strict"

const Enum = require('enumify').Enum

class PuttingFileType extends Enum {
}

PuttingFileType.initEnum([
  'APPLICATION_LEVEL_JAVASCRIPT_DIRECTORY',
  'APPLICATION_LEVEL_JAVASCRIPT',
  'GLOBAL_SNIPPETS_DIRECTORY',
  'GLOBAL_SNIPPETS_LOCALE_DIRECTORY',
  'GLOBAL_SNIPPETS',
  'THEMES_DIRECTORY',
  'THEME',
  'THEME_STYLES',
  'THEME_ADDITIONAL_STYLES',
  'THEME_VARIABLES',
  'GLOBAL_ELEMENTS_DIRECTORY',
  'GLOBAL_ELEMENT',
  'GLOBAL_ELEMENT_TEMPLATE',
  'GLOBAL_ELEMENT_JAVASCRIPT',
  'WIDGET',
  'WIDGETS_DIRECTORY',
  'WIDGET_BASE_TEMPLATE',
  'WIDGET_BASE_LESS',
  'WIDGET_BASE_SNIPPETS',
  'WIDGET_JAVASCRIPT',
  'WIDGET_METADATA_JSON',
  'WIDGET_INSTANCE',
  'WIDGET_INSTANCE_METADATA_JSON',
  'WIDGET_INSTANCE_TEMPLATE',
  'WEB_CONTENT_TEMPLATE',
  'WIDGET_INSTANCE_LESS',
  'WIDGET_INSTANCE_SNIPPETS',
  'WIDGET_CONFIG_SNIPPETS',
  'WIDGET_CONFIG_JSON',
  'ELEMENT_TEMPLATE',
  'ELEMENT_JAVASCRIPT',
  'STACKS_DIRECTORY',
  'STACK',
  'STACK_INSTANCE_LESS',
  'STACK_INSTANCE_VARIABLES_LESS',
  'STACK_INSTANCE_TEMPLATE'
])

exports.PuttingFileType = PuttingFileType
